# Default agora variables are set here
DEFAULT_AGORA_VARIABLES = {"DEFAULT_COST": 50}

AGORA_DEFAULT_COST_MODEL = "default => $DEFAULT_COST * $GLOBAL_COST_MULTIPLIER;"

AGORA_ENTRY_TEMPLATE = """\
# Generated by AutoAgora {{aa_version}}
{% for frequent_query in most_frequent_queries %}

# count:        {{frequent_query.count}}
# min time:     {{frequent_query.min_time}}
# max time:     {{frequent_query.max_time}}
# avg time:     {{frequent_query.avg_time}}
# stddev time:  {{frequent_query.stddev_time}}
{{frequent_query.query}} => {{frequent_query.avg_time}} * $GLOBAL_COST_MULTIPLIER;
{% endfor %}
{% if manual_entry is not none %}
{{manual_entry}}
{% endif %}
default => $DEFAULT_COST * $GLOBAL_COST_MULTIPLIER;\
"""
