name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ubuntu-latest
    env:
      # https://github.com/actions/runner-images/issues/6185
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    steps:
      - uses: actions/checkout@v3

      - run: curl -sSL https://install.python-poetry.org | python3 -

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Black formatter
        run: poetry run black --check --diff --color .

      - name: Isort formatter
        run: poetry run isort --check --diff .

      - name: Pyright static type checks
        run: poetry run pyright .

      - name: Install pytest github annotation plugin
        run: poetry run pip install pytest-github-actions-annotate-failures

      - name: "Pytest: unit tests"
        run: poetry run pytest --cov=autoagora --cov-report=lcov

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
